- hosts: guests:extras
  become: yes
  gather_facts: yes
  tasks:
    - name: create mysqldump
      get_url: url=https://github.com/catatsuy/private-isu/releases/download/img/dump.sql.bz2 dest=/home/isucon/backup/mysqldump.sql.bz2 force=1
    - name: create database
      shell: bzcat /home/isucon/backup/mysqldump.sql.bz2 | mysql -u root
