AWSTemplateFormatVersion: "2010-09-09"
Description: EC2 instance using a prebuilt AMI

Parameters:
  KeyName:
    Type: AWS::EC2::KeyPair::KeyName
    Description: Name of an existing EC2 KeyPair to SSH

Resources:
  MyInstance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: c7a.large
      KeyName: !Ref KeyName
      ImageId: ami-02571aa4b7a43569c
      SecurityGroupIds:
        - !Ref MySecurityGroup
      Tags:
        - Key: Name
          Value: ISUCON Machine

  MySecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow HTTP and SSH
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
